name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        images:
          - 3.13-2.1.3
          - 3.12-2.1.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from file
        id: get_version
        run: |
          VERSION=$(cat ./${{ matrix.images }}/version.txt | tr -d ' \n')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # https://github.com/rust-lang/cargo/issues/7451
      - name: Arm cargo bugfix
        run: |
          mkdir /tmp/cargo
          sudo mount -t tmpfs -o size=10G tmpfs /tmp/cargo

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./${{ matrix.images }}
          platforms: linux/amd64,linux/arm/v6,linux/arm64
          push: true
          tags: cyberbarrista/python-with-poetry:${{ matrix.images }}_${{ steps.get_version.outputs.version }}
